interface Policy {
  id: number;
  clientName: string;
  type: string;
  insuranceCompany: string;
  policyNumber: string;
  policyStatus: string;
  sumInsured: string;
  expiryDate: string;
  commissionStatus: string;
  commission: string;
  remarks: string;
}
export const policies: Policy[] = [
    {
        id: 40,
        clientName: "John Doe",
        type: "Car",
        insuranceCompany: "AllState Insurance",
        policyNumber: "POL12345",
        policyStatus: "Expired",
        sumInsured: "$20,000",
        expiryDate: "2024-05-15",
        commissionStatus: "Recieved",
        commission: "31 Ft (10%)",
        remarks: "",
    },
    {
        id: 40,
        clientName: "John Doe",
        type: "Car",
        insuranceCompany: "AllState Insurance",
        policyNumber: "POL12345",
        policyStatus: "Expired",
        sumInsured: "$20,000",
        expiryDate: "2024-05-15",
        commissionStatus: "Recieved",
        commission: "31 Ft (10%)",
        remarks: "",
    },
    {
        id: 40,
        clientName: "John Doe",
        type: "Car",
        insuranceCompany: "AllState Insurance",
        policyNumber: "POL12345",
        policyStatus: "Expired",
        sumInsured: "$20,000",
        expiryDate: "2024-05-15",
        commissionStatus: "Recieved",
        commission: "31 Ft (10%)",
        remarks: "",
    },
    {
        id: 40,
        clientName: "John Doe",
        type: "Car",
        insuranceCompany: "AllState Insurance",
        policyNumber: "POL12345",
        policyStatus: "Expired",
        sumInsured: "$20,000",
        expiryDate: "2024-05-15",
        commissionStatus: "Recieved",
        commission: "31 Ft (10%)",
        remarks: "",
    },
    {
        id: 40,
        clientName: "John Doe",
        type: "Car",
        insuranceCompany: "AllState Insurance",
        policyNumber: "POL12345",
        policyStatus: "Expired",
        sumInsured: "$20,000",
        expiryDate: "2024-05-15",
        commissionStatus: "Recieved",
        commission: "31 Ft (10%)",
        remarks: "",
    },
    {
        id: 40,
        clientName: "John Doe",
        type: "Car",
        insuranceCompany: "AllState Insurance",
        policyNumber: "POL12345",
        policyStatus: "Expired",
        sumInsured: "$20,000",
        expiryDate: "2024-05-15",
        commissionStatus: "Recieved",
        commission: "31 Ft (10%)",
        remarks: "",
    },
    {
        id: 40,
        clientName: "John Doe",
        type: "Car",
        insuranceCompany: "AllState Insurance",
        policyNumber: "POL12345",
        policyStatus: "Expired",
        sumInsured: "$20,000",
        expiryDate: "2024-05-15",
        commissionStatus: "Recieved",
        commission: "31 Ft (10%)",
        remarks: "",
    },
    {
        id: 65,
        clientName: "Jane Smith",
        type: "Health",
        insuranceCompany: "HealthGuard",
        policyNumber: "POL67890",
        policyStatus: "Pending",
        sumInsured: "$50,000",
        expiryDate: "2023-11-30",
        commissionStatus: "Pending",
        commission: "",
        remarks: "",
    },
    {
        id: 74,
        clientName: "Michael Johnson",
        type: "Fire",
        insuranceCompany: "SafeHome Insurance",
        policyNumber: "POL54321",
        policyStatus: "",
        sumInsured: "$100,000",
        expiryDate: "2025-01-20",
        commissionStatus: "",
        commission: "31 Ft (10%)",
        remarks: "",
    },
    {
        id: 21,
        clientName: "Emily Brown",
        type: "Car",
        insuranceCompany: "DriveSafe Insurance",
        policyNumber: "POL98765",
        policyStatus: "",
        sumInsured: "$15,000",
        expiryDate: "2024-08-10",
        commissionStatus: "",
        commission: "",
        remarks: "",
    },
    {
        id: 96,
        clientName: "David Wilson",
        type: "Health",
        insuranceCompany: "WellCare Insurance",
        policyNumber: "POL24680",
        policyStatus: "",
        sumInsured: "$30,000",
        expiryDate: "2023-12-01",
        commissionStatus: "",
        commission: "",
        remarks: "",
    },
];
