export type PolicyType = "Motor" | "Fire" | "Life" | "Health" | "Travel";
export type PolicyStatus = "Active" | "Expired";
export type CommissionStatus = "Pending" | "Paid";
export type CompanyName = "AYA SOMPO" | "GGI" | "YOUNG" | "IKBZ" | "FNI";
export type Policy = {
  id: number;
  clientName: string;
  clientContact: string;
  policyType: PolicyType;
  companyName: CompanyName;
  policyNumber: string;
  policyStatus: PolicyStatus;
  sumInsured: number;
  startDate: string;
  expiryDate: string;
  commissionStatus: CommissionStatus;
  commissionAmount: number;
  commissionRate: number;
  remarks?: string;
}

export const COLUMNS = {
    clientName: "Client Name",
    policyNumber: "Policy Number",
    policyStatus: "Policy Status",
    commissionStatus: "Commission Status",
    expirationDate: "Expiration Date",
    sumInsured: "Sum Insured",
    startDate: "Start Date",
    expiryDate: "Expiry Date",
    commissionAmount: "Commission Amount",
    commissionRate: "Commission Rate",
    remarks: "Remarks",
    companyName: "Company Name",
    policyType: "Policy Type",
    clientContact: "Client Contact",
};

export const policyTypes: PolicyType[] = ["Motor", "Fire", "Life", "Health", "Travel"];
export const policyStatuses: PolicyStatus[] = ["Active", "Expired"];
export const commissionStatuses: CommissionStatus[] = ["Pending", "Paid"];
export const companyNames: CompanyName[] = ["AYA SOMPO", "GGI", "YOUNG", "IKBZ", "FNI"];

export const policies: Policy[] = [
    {
        id: 1,
        clientName: "John Doe",
        clientContact: "08123456789",
        policyType: "Motor",
        companyName: "AYA SOMPO",
        policyNumber: "1234567890",
        policyStatus: "Active",
        sumInsured: 20000,
        startDate: "May 15 2024",
        expiryDate: "May 15 2025",
        commissionStatus: "Pending",
        commissionAmount: 1000,
        commissionRate: 10,
    },
    {
        id: 2,
        clientName: "Jane Smith",
        clientContact: "09123456789",
        policyType: "Fire",
        companyName: "GGI",
        policyNumber: "9876543210",
        policyStatus: "Expired",
        sumInsured: 50000,
        startDate: "Jan 20 2023",
        expiryDate: "Jan 20 2023",
        commissionStatus: "Paid",
        commissionAmount: 500,
        commissionRate: 5,
    },
    {
        id: 3,
        clientName: "Alice Johnson",
        clientContact: "08098765432",
        policyType: "Fire",
        companyName: "YOUNG",
        policyNumber: "2468135790",
        policyStatus: "Active",
        sumInsured: 100000,
        startDate: "Jan 20 2023",
        expiryDate: "Jan 20 2024",
        commissionStatus: "Pending",
        commissionAmount: 2000,
        commissionRate: 2,
    },
    {
        id: 4,
        clientName: "Bob Williams",
        clientContact: "08123456700",
        policyType: "Fire",
        companyName: "IKBZ",
        policyNumber: "1357908642",
        policyStatus: "Active",
        sumInsured: 75000,
        startDate: "Jul 01 2023",
        expiryDate: "Jul 01 2024",
        commissionStatus: "Paid",
        commissionAmount: 1500,
        commissionRate: 2,
    },
    {
        id: 5,
        clientName: "Charlie Brown",
        clientContact: "08012345678",
        policyType: "Motor",
        companyName: "AYA SOMPO",
        policyNumber: "1122334455",
        policyStatus: "Expired",
        sumInsured: 15000,
        startDate: "Sep 12 2022",
        expiryDate: "Sep 12 2023",
        commissionStatus: "Paid",
        commissionAmount: 750,
        commissionRate: 5,
    },
    {
        id: 6,
        clientName: "David Wilson",
        clientContact: "08223456712",
        policyType: "Motor",
        companyName: "FNI",
        policyNumber: "3344556677",
        policyStatus: "Active",
        sumInsured: 25000,
        startDate: "Feb 14 2024",
        expiryDate: "Feb 14 2025",
        commissionStatus: "Pending",
        commissionAmount: 1250,
        commissionRate: 5,
    },
    {
        id: 7,
        clientName: "Emily Davis",
        clientContact: "08456789123",
        policyType: "Life",
        companyName: "GGI",
        policyNumber: "9988776655",
        policyStatus: "Active",
        sumInsured: 80000,
        startDate: "Jun 21 2023",
        expiryDate: "Oct 29 2024",
        commissionStatus: "Paid",
        commissionAmount: 1600,
        commissionRate: 2,
    },
    {
        id: 8,
        clientName: "Frank Thompson",
        clientContact: "08091234567",
        policyType: "Fire",
        companyName: "YOUNG",
        policyNumber: "2244668800",
        policyStatus: "Expired",
        sumInsured: 90000,
        startDate: "Aug 30 2022",
        expiryDate: "Oct 30 2023",
        commissionStatus: "Paid",
        commissionAmount: 1800,
        commissionRate: 2,
    },
    {
        id: 9,
        clientName: "Grace Lee",
        clientContact: "08623456790",
        policyType: "Fire",
        companyName: "AYA SOMPO",
        policyNumber: "6677889900",
        policyStatus: "Active",
        sumInsured: 60000,
        startDate: "Nov 15 2023",
        expiryDate: "Nov 20 2024",
        commissionStatus: "Pending",
        commissionAmount: 1200,
        commissionRate: 2,
    },
    {
        id: 10,
        clientName: "Henry Walker",
        clientContact: "08765432198",
        policyType: "Travel",
        companyName: "IKBZ",
        policyNumber: "5566778899",
        policyStatus: "Active",
        sumInsured: 30000,
        startDate: "Jan 11 2024",
        expiryDate: "Jan 11 2025",
        commissionStatus: "Pending",
        commissionAmount: 1500,
        commissionRate: 5,
    },
    {
        id: 11,
        clientName: "Ivy Evans",
        clientContact: "08887654321",
        policyType: "Motor",
        companyName: "GGI",
        policyNumber: "4433221100",
        policyStatus: "Expired",
        sumInsured: 18000,
        startDate: "Nov 05 2022",
        expiryDate: "Nov 05 2023",
        commissionStatus: "Paid",
        commissionAmount: 900,
        commissionRate: 5,
    },
    {
        id: 12,
        clientName: "Jack Harris",
        clientContact: "08323456789",
        policyType: "Fire",
        companyName: "FNI",
        policyNumber: "1011121314",
        policyStatus: "Active",
        sumInsured: 100000,
        startDate: "Sep 01 2023",
        expiryDate: "Sep 01 2024",
        commissionStatus: "Pending",
        commissionAmount: 2000,
        commissionRate: 2,
    },
    {
        id: 13,
        clientName: "Karen Garcia",
        clientContact: "08543219876",
        policyType: "Life",
        companyName: "AYA SOMPO",
        policyNumber: "2233445566",
        policyStatus: "Expired",
        sumInsured: 120000,
        startDate: "Dec 31 2021",
        expiryDate: "Dec 31 2023",
        commissionStatus: "Paid",
        commissionAmount: 2400,
        commissionRate: 2,
    },
    {
        id: 14,
        clientName: "Larry Martinez",
        clientContact: "08901234567",
        policyType: "Health",
        companyName: "IKBZ",
        policyNumber: "8899007766",
        policyStatus: "Active",
        sumInsured: 70000,
        startDate: "Oct 10 2023",
        expiryDate: "Oct 10 2024",
        commissionStatus: "Pending",
        commissionAmount: 1400,
        commissionRate: 2,
    },
    {
        id: 15,
        clientName: "Megan Anderson",
        clientContact: "08345678912",
        policyType: "Travel",
        companyName: "YOUNG",
        policyNumber: "9988776655",
        policyStatus: "Active",
        sumInsured: 25000,
        startDate: "Dec 12 2023",
        expiryDate: "Dec 12 2024",
        commissionStatus: "Paid",
        commissionAmount: 1250,
        commissionRate: 5,
    },
];
